In [1]:
import numpy as np 
import pandas as pd 
import random 

In [2]:
x = np.random.rand(100,1)

In [47]:
y =  4 + 3*x + np.random.randn(100,1)

In [26]:
x_b = np.c_[np.ones((100,1)), x]

In [48]:
np.linalg.inv(x_b.T.dot(x_b)).dot(x_b.T).dot(y)

array([[3.90894905],
       [3.04113525]])

In [54]:
[np.linalg.inv(x_b.T.dot(x_b)).dot(x_b.T).dot(y).T.dot(x_b[i]) for i in range(0, len(y))]
    

[array([6.63709079]),
 array([5.04398875]),
 array([6.30686164]),
 array([6.68987921]),
 array([5.13094958]),
 array([4.9175821]),
 array([6.75705898]),
 array([6.78644794]),
 array([5.98026072]),
 array([4.92033189]),
 array([4.02073864]),
 array([5.37537202]),
 array([4.76564511]),
 array([5.48481982]),
 array([6.89862657]),
 array([5.28509878]),
 array([6.76431397]),
 array([5.8047342]),
 array([6.19695001]),
 array([6.08693536]),
 array([6.86383724]),
 array([6.70462229]),
 array([4.48327745]),
 array([5.22886582]),
 array([5.23887728]),
 array([5.44981773]),
 array([5.63348714]),
 array([4.83512777]),
 array([5.88957931]),
 array([5.78324171]),
 array([5.44870456]),
 array([5.57679486]),
 array([3.9575205]),
 array([6.78799345]),
 array([4.36163771]),
 array([6.18629157]),
 array([4.78260115]),
 array([6.49791888]),
 array([6.82769908]),
 array([6.75995657]),
 array([6.684806]),
 array([6.50981987]),
 array([5.91095745]),
 array([4.88612128]),
 array([6.19444511]),
 array([4.08556

In [51]:
x_b[0]

array([1.        , 0.89708004])